name: 'Ref Tracker'
description: 'Looks up mutable refs in config files and writes out immutable versions'
author: 'Apollo GraphQL'

# Define your inputs here.
inputs:
  files:
    description: 'Glob pattern for files to search'
    required: true

  github-token:
    description: 'GitHub token to read refs and trees; only needed if update-git-refs is set'
  
  update-git-refs:
    description: 'Process trackMutableRef instructions'
    default: 'false'
  
  update-docker-tags-for-artifact-registry-repository:
    description: 'Process trackMutableTag instructions; must be set to a string of the form `projects/PROJECT/locations/LOCATION/repositories/REPOSITORY`'
  
  update-promoted-values:
    description: 'Process promote instructions'
    default: 'false'
  
  promotion-target-regexp:
    description: 'Only process promote instructions for targets matching this regexp'

runs:
  using: node20
  main: dist/index.js
