name: 'Ref Tracker'
description: 'Looks up mutable refs in config files and writes out immutable versions'
author: 'Apollo GraphQL'

# Define your inputs here.
inputs:
  files:
    description: 'Glob pattern for files to search'
    required: true

runs:
  using: node20
  main: dist/index.js
